name: Build Proxmox Backup Client

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sundays

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
      options: --privileged
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup system
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm git sudo base-devel util-linux glibc

      - name: Create build environment
        run: |
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/builder
          mkdir -p /opt/builds
          chown -R builder:builder /opt/builds

      - name: Clone AUR package
        run: |
          cd /opt/builds
          sudo -u builder git clone --depth=1 https://aur.archlinux.org/proxmox-backup-client.git
          chown -R builder:builder proxmox-backup-client

      - name: Build package
        run: |
          cd /opt/builds/proxmox-backup-client
          sudo -u builder makepkg -s --noconfirm

      - name: Create package repository
        run: |
          mkdir -p repo/custom/os/x86_64
          mv /opt/builds/proxmox-backup-client/*.pkg.tar.zst repo/archlinux/custom/os/x86_64/
          cd repo/archlinux/custom/os/x86_64
          repo-add custom.db.tar.gz *.pkg.tar.zst

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./repo
          publish_branch: repo
          force_orphan: true
          enable_jekyll: false
          commit_message: "Update package repository"

      - name: Upload package artifacts
        uses: actions/upload-artifact@v3
        with:
          name: proxmox-backup-client-package
          path: repo/archlinux/custom/os/x86_64/*.pkg.tar.zst
